update CI/CD file

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,22 +7,155 @@ on:
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
   BUILD_TYPE: Release
-  BOOST_VERSION: 78
-  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+  BOOST_VERSION: 1.78.0
+  APPLICATION_VERSION: 0.1.0
+  APPLICATION_NAME: HangmanGame
 
 permissions: write-all
 
 jobs:
 
- build-client:
+ sonarcloud-analyse:
+    env:
+      BUILD_TYPE: Debug
     runs-on: ubuntu-latest
     steps:
 
     - uses: actions/checkout@v2
-      
+      with:
+        # Disabling shallow clone is recommended for improving relevancy of reporting
+        fetch-depth: 0
+
+    - name: Install dependencies
+      run: sudo apt-get install -y clang-tidy cppcheck default-libmysqlclient-dev odb libodb-dev libodb-mysql-2.4 mysql-community-client-plugins mysql-common
+
+    - name: Create reports directory (server)
+      run: mkdir ${{github.workspace}}/server/reports
+
+    - name: Lint Cpp Check (server)
+      run: cppcheck --enable=all --inconclusive --language=c++ --std=c++20 --xml --output-file=${{github.workspace}}/server/reports/cppcheck_report.xml ${{github.workspace}}/server
+
+    - name: Install boost
+      uses: MarkusJx/install-boost@v2.0.0
+      id: install-boost
+      with:
+        boost_version: ${{env.BOOST_VERSION}}
+
+    - name: Generate Model Sources
+      working-directory: ${{github.workspace}}/data-management/src/model
+      run: odb -d mysql --generate-query --generate-schema user.hxx; ls -a .
+
+    - name: Create reports directory
+      run: mkdir ${{github.workspace}}/data-management/reports
+
+    - name: Lint Cpp Check
+      run: cppcheck --enable=all --inconclusive --language=c++ --std=c++20 --xml --output-file=${{github.workspace}}/data-management/reports/cppcheck_report.xml ${{github.workspace}}/data-management
+
+    - name: Start MySQL server
+      run: sudo service mysql start 
+
+    - name: Update Database schema
+      run: sudo mysql -e '${{env.DB_POPULATE}}' --user=${{env.DB_USER}} --password=${{env.DB_PWD}}
+
+    - name: Update Database schema
+      working-directory: ${{github.workspace}}/data-management/src/model
+      run:  mysql --user=odb_test --database=odb_test < user.sql
+
+    - name: Generate target (data management)
+      run: cmake -S ${{github.workspace}}/data-management -B ${{github.workspace}}/data-management/bin -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES=OFF -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
+      env:
+        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
+
+    - name: Build Data Management
+      working-directory: ${{github.workspace}}/data-management
+      run: cmake --build ${{github.workspace}}/data-management/bin
+
+    - name: Test Data Management
+      working-directory: ${{github.workspace}}/data-management/bin
+      run: ctest --verbose
+
+    - name: Lint Clang-Tidy (data-management)
+      run: clang-tidy -checks='*' -header-filter='data-management/src/.*' -p data-management/bin data-management/**/*.*pp > ${{github.workspace}}/data-management/reports/clang_tidy_report.txt
+
+    - name: Download cpp-coso ${{env.CPP_COSO_VERSION}}
+      uses: wei/wget@v1
+      with:
+        args: -O cpp-coso-${{env.CPP_COSO_VERSION}}-Linux.deb https://mguillaumef.github.io/cpp-coso/delivery/${{env.CPP_COSO_VERSION}}/cpp-coso-${{env.CPP_COSO_VERSION}}-Linux.deb
+
+    - name: Install cpp-coso
+      run: sudo dpkg -i cpp-coso-${{env.CPP_COSO_VERSION}}-Linux.deb
+
+    - name: Convert Lint Clang-Tidy to sonarqube format (data-management)
+      run: /usr/cpp-coso/cpp-coso clang-tidy ${{github.workspace}}/data-management/reports/clang_tidy_report.txt ${{github.workspace}}/data-management/reports/clang-tidy-sonarqube-report.json
+
+    - name: Convert Lint Cpp Check to sonarqube format
+      run: /usr/cpp-coso/cpp-coso cppcheck ${{github.workspace}}/server/reports/cppcheck_report.xml ${{github.workspace}}/server/reports/cppcheck-sonarqube-report.json
+
+    - name: Convert Lint Cpp Check to sonarqube format (data-management)
+      run: /usr/cpp-coso/cpp-coso cppcheck ${{github.workspace}}/data-management/reports/cppcheck_report.xml ${{github.workspace}}/data-management/reports/cppcheck-sonarqube-report.json
+
+    - name: Archive data-management report
+      uses: actions/upload-artifact@v2
+      with:
+        name: Data-Management-Hangman-Game - Reports
+        path: ${{github.workspace}}/data-management/reports
+
+    - name: Generate target
+      run: cmake -S ${{github.workspace}}/server -B ${{github.workspace}}/server/bin -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES=OFF -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
+      env:
+        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
+
+    - name: Build server
+      working-directory: ${{github.workspace}}/server
+      # Build your program with the given configuration
+      run: cmake --build ${{github.workspace}}/server/bin
+
+    - name: Lint Clang-Tidy
+      run: clang-tidy -checks='*,-modernize-use-trailing-return-type,-llvm-header-guard,-fuchsia-default-arguments-calls,-fuchsia-default-arguments-declarations' -header-filter='server/src/.*' -p server/bin server/**/*.*pp > ${{github.workspace}}/server/reports/clang_tidy_report.txt
+
+    - name: Convert Lint Clang-Tidy to sonarqube format
+      run: /usr/cpp-coso/cpp-coso clang-tidy ${{github.workspace}}/server/reports/clang_tidy_report.txt ${{github.workspace}}/server/reports/clang-tidy-sonarqube-report.json
+
+    - name: Server Tests ctest
+      working-directory: ${{github.workspace}}/server/test
+      run: |
+        chmod +x ./run-tests.sh
+        ./run-tests.sh
+
+    - name: Merge Coverage
+      if: github.actor != 'dependabot[bot]'
+      run: | 
+        cp -r ${{github.workspace}}/server/bin/CMakeFiles/HangmanGame.dir/src ${{github.workspace}}/server/bin/coverage
+        gcov-tool merge --output ${{github.workspace}}/server/bin/coverage --verbose ${{github.workspace}}/server/bin/CMakeFiles/HangmanGame.dir/src ${{github.workspace}}/server/bin/CMakeFiles/HangmanGameTest.dir/src
+
+    - name: gcov after merge
+      if: github.actor != 'dependabot[bot]'
+      working-directory: ${{github.workspace}}/server/bin/coverage
+      run: find -name '*.gcda' | xargs gcov
+
+    - name: Archive Test report
+      uses: actions/upload-artifact@v2
+      with:
+        name: Server-Hangman-Game - Reports
+        path: ${{github.workspace}}/server/reports
+
     - name: Install client's dependencies
       working-directory: ${{github.workspace}}/client
       run: npm install
+
+    - name: Prettier format
+      if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
+      working-directory: ${{github.workspace}}/client
+      run: |
+        git checkout ${{github.head_ref}}
+        npm run prettier
+        git config user.name "MGuillaumeF"
+        git config user.email "${{secrets.EMAIL}}"
+        git add .
+        (git commit -m "[AUTO] prettier format write" && git push) || echo 'No modification to save'
+       
+      env:
+        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
     - name: Build client
       working-directory: ${{github.workspace}}/client
@@ -34,8 +167,79 @@ jobs:
         name: IHM-Hangman-Game
         path: ${{github.workspace}}/client/build
 
- build-server-linux:
-    needs: [build-client]
+    - name: Client tests
+      working-directory: ${{github.workspace}}/client
+      run: npm start & (npm run cy:run && kill $(lsof -t -i:3000))
+
+    - name: Archive IHM Tests videos 
+      uses: actions/upload-artifact@v2
+      with:
+        name: IHM-Hangman-Game-Tests-Videos 
+        path: ${{github.workspace}}/client/cypress/videos
+
+    - name: Print summary coverage
+      working-directory: ${{github.workspace}}/client
+      run: npx nyc report --reporter=lcov --reporter=text-summary
+
+    - name: ESlint analyze json
+      working-directory: ${{github.workspace}}/client
+      run: npm run lint:eslint:json || echo FAILED
+
+    - name: ESlint analyze html
+      working-directory: ${{github.workspace}}/client
+      run: npm run lint:eslint || echo FAILED
+
+    - name: Audit dependency
+      working-directory: ${{github.workspace}}/client
+      run: npm audit --json > ./dist/reports/audit-dependency-report.json || echo FAILED
+
+    - name: Convert Audit dependency report
+      working-directory: ${{github.workspace}}/client
+      run: ./node_modules/.bin/audiso --input-file=./dist/reports/audit-dependency-report.json --output-file ./dist/reports/audit-report.json
+
+    - name: Stylelint analyze
+      working-directory: ${{github.workspace}}/client
+      run: npm run lint:stylelint
+
+    - name: Archive Analyses reports
+      uses: actions/upload-artifact@v2
+      with:
+        name: IHM-Hangman-Game-Analyses-report
+        path: ${{github.workspace}}/client/dist
+
+    - name: Setup sonarqube
+      if: github.actor != 'dependabot[bot]'
+      uses: warchant/setup-sonar-scanner@v3
+
+    - name: Run SonarQube data-management
+      working-directory: ${{github.workspace}}/data-management
+      if: github.actor != 'dependabot[bot]'
+      env:
+        GITHUB_TOKEN: ${{ secrets.SONAR_REPO_ACCESS_TOKEN }}
+      run: sonar-scanner
+        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
+        -Dsonar.verbose=false
+
+    - name: Run SonarQube
+      if: github.actor != 'dependabot[bot]'
+      env:
+        GITHUB_TOKEN: ${{ secrets.SONAR_REPO_ACCESS_TOKEN }}
+      run: sonar-scanner
+        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
+        -Dsonar.verbose=false
+
+    - name: SonarQube Quality Gate check
+      if: github.actor != 'dependabot[bot]'
+      uses: sonarsource/sonarqube-quality-gate-action@master
+      # Force to fail step after specific time
+      timeout-minutes: 5
+      env:
+       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+ build-release-Linux:
+    needs: [sonarcloud-analyse]
     runs-on: ubuntu-latest
     steps:
 
@@ -53,7 +257,7 @@ jobs:
       uses: MarkusJx/install-boost@v2.0.0
       id: install-boost
       with:
-        boost_version: 1.${{env.BOOST_VERSION}}.0
+        boost_version: ${{env.BOOST_VERSION}}
 
     - name: Generate target
       run: cmake -S ${{github.workspace}}/server -B ${{github.workspace}}/server/bin -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES=OFF -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
@@ -83,7 +287,7 @@ jobs:
         path: ${{github.workspace}}/server/bin/HangmanGame-0.1.0-Linux.deb
 
  install-server-linux:
-    needs: [build-server-linux]
+    needs: [build-release-Linux]
     runs-on: ubuntu-latest
     steps:
 
@@ -101,8 +305,10 @@ jobs:
     #   working-directory: /usr/HangmanGame
     #   run: ./HangmanGame
 
- build-server-win:
-    needs: [build-client]
+ build-debug-Windows:
+    env:
+      BUILD_TYPE: Debug
+    needs: [sonarcloud-analyse]
     runs-on: windows-latest
     steps:
 
@@ -117,9 +323,7 @@ jobs:
       uses: MarkusJx/install-boost@v2.0.0
       id: install-boost
       with:
-        boost_version: 1.${{env.BOOST_VERSION}}.0
-        # OPTIONAL: Specify a platform version
-        platform_version: 2019
+        boost_version: ${{env.BOOST_VERSION}}
         # OPTIONAL: in workspace by default
         boost_install_dir: 'D:/'
 
@@ -131,27 +335,76 @@ jobs:
     - name: Build server windows
       working-directory: ${{github.workspace}}/server
       # Build your program with the given configuration
-      run: cmake --build ${{github.workspace}}/server/bin
+      run: cmake --build ${{github.workspace}}/server/bin --config ${{env.BUILD_TYPE}}
 
-    # - name: Package server
-    #   working-directory: ${{github.workspace}}/server/bin
-    #   # Build your program with the given configuration
-    #   run: cpack -G "ZIP;NSIS"
+    - name: Unit Tests
+      working-directory: ${{github.workspace}}/server/bin
+      run: ctest --verbose
 
-    # - name: Archive Server windows ZIP
-    #   uses: actions/upload-artifact@v2
-    #   with:
-    #     name: Server-Hangman-Game-Win
-    #     path: ${{github.workspace}}/server/bin/HangmanGame-0.1.0-win64.exe
+ build-release-Windows:
+    needs: [sonarcloud-analyse]
+    runs-on: windows-latest
+    steps:
 
-    # - name: Archive Server windows NSIS
-    #   uses: actions/upload-artifact@v2
-    #   with:
-    #     name: Server-Hangman-Game-Win
-    #     path: ${{github.workspace}}/server/bin/HangmanGame-0.1.0-win64.exe
+    - uses: actions/checkout@v2
+
+    - uses: actions/download-artifact@v2
+      with:
+        name: IHM-Hangman-Game
+        path: ${{github.workspace}}/client/build
+
+    - name: Install boost
+      uses: MarkusJx/install-boost@v2.0.0
+      id: install-boost
+      with:
+        boost_version: ${{env.BOOST_VERSION}}
+        # OPTIONAL: in workspace by default
+        boost_install_dir: 'D:/'
+
+    - name: Generate target 
+      run: cmake -S ${{github.workspace}}/server -B ${{github.workspace}}/server/bin -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
+      env:
+        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
+
+    - name: Build server windows
+      working-directory: ${{github.workspace}}/server
+      # Build your program with the given configuration
+      run: cmake --build ${{github.workspace}}/server/bin --config ${{env.BUILD_TYPE}}
+
+    - name: Package server
+      working-directory: ${{github.workspace}}/server/bin
+      # Build your program with the given configuration
+      run: cpack -G "ZIP;NSIS64"
+
+    - name: Archive Application windows ZIP
+      uses: actions/upload-artifact@v2
+      with:
+        name: ${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-win64.zip
+        path: ${{github.workspace}}/server/bin/${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-win64.zip
+
+    - name: Archive Application windows NSIS 64
+      uses: actions/upload-artifact@v2
+      with:
+        name: ${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-win64.exe
+        path: ${{github.workspace}}/server/bin/${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-win64.exe
+
+ install-Windows:
+    needs: [build-release-Windows]
+    runs-on: windows-latest
+    steps:
+
+    - uses: actions/download-artifact@v2
+      with:
+        name: ${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-win64.exe
+
+    - name: install
+      run: cmd /C "${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-win64.exe /S"
+
+    - name: run
+      run: 'tree "C:\program files\${{env.APPLICATION_NAME}}\${{env.APPLICATION_NAME}}"'
 
  build-server-MacOSX:
-    needs: [build-client]
+    needs: [sonarcloud-analyse]
     runs-on: macos-11
     steps:
 
@@ -166,7 +419,7 @@ jobs:
       uses: MarkusJx/install-boost@v2.0.0
       id: install-boost
       with:
-        boost_version: 1.${{env.BOOST_VERSION}}.0
+        boost_version: ${{env.BOOST_VERSION}}
 
     - name: Generate target
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
@@ -180,13 +433,18 @@ jobs:
       # Build your program with the given configuration
       run: cmake --build ${{github.workspace}}/server/bin
 
-    - name: Package server
+    - name: Package Application
       working-directory: ${{github.workspace}}/server/bin
-      # Build your program with the given configuration
-      run: cpack -G "ZIP"
+      run: cpack -G "ZIP;DragNDrop"
 
-    - name: Archive Server ZIP
+    - name: Archive Application ZIP
       uses: actions/upload-artifact@v2
       with:
-        name: Server-Hangman-Game-MacOSX
-        path: ${{github.workspace}}/server/bin/HangmanGame-0.1.0-Darwin.zip
+        name: ${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-Darwin.zip
+        path: ${{github.workspace}}/server/bin/${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-Darwin.zip
+
+    - name: Archive Application DMG
+      uses: actions/upload-artifact@v2
+      with:
+        name: ${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-Darwin.dmg
+        path: ${{github.workspace}}/server/bin/${{env.APPLICATION_NAME}}-${{env.APPLICATION_VERSION}}-Darwin.dmg
